src/AppBundle/Entity/Comment.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="comments")
 */
class Comment
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $userName;

    /**
     * @ORM\Column(type="string")
     */
    protected $comment;

    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $userEmail;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @Assert\File(mimeTypes={"image/*"})
     */
    protected $avatar;

    /**
     * @ORM\Column(type="integer")
     */
    protected $createdAt;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $moderated;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set createdAt
     *
     * @param integer $createdAt
     *
     * @return Comment
     */
    public function setCreatedAt($createdAt)
    {
        if ($createdAt instanceof \DateTime) {
            $this->createdAt = $createdAt->getTimestamp();
        } else {
            $this->createdAt = $createdAt;
        }

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return integer
     */
    public function getCreatedAt()
    {
        return (integer) $this->createdAt;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAtAsDate()
    {
        return (new \DateTime())->setTimestamp($this->createdAt);
    }

    /**
     * Set userName
     *
     * @param string $userName
     *
     * @return Comment
     */
    public function setUserName($userName)
    {
        $this->userName = $userName;

        return $this;
    }

    /**
     * Get userName
     *
     * @return string
     */
    public function getUserName()
    {
        return $this->userName;
    }

    /**
     * Set userEmail
     *
     * @param string $userEmail
     *
     * @return Comment
     */
    public function setUserEmail($userEmail)
    {
        $this->userEmail = $userEmail;

        return $this;
    }

    /**
     * Get userEmail
     *
     * @return string
     */
    public function getUserEmail()
    {
        return $this->userEmail;
    }

    /**
     * Set comment
     *
     * @param string $comment
     *
     * @return Comment
     */
    public function setComment($comment)
    {
        $this->comment = $comment;

        return $this;
    }

    /**
     * Get comment
     *
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * Set pathFile
     *
     * @param string $pathFile
     *
     * @return Comment
     */
    public function setPathFile($pathFile)
    {
        $this->pathFile = $pathFile;

        return $this;
    }

    /**
     * Get pathFile
     *
     * @return string
     */
    public function getPathFile()
    {
        return $this->pathFile;
    }

    /**
     * Set moderated
     *
     * @param boolean $moderated
     *
     * @return Comment
     */
    public function setModerated($moderated)
    {
        $this->moderated = $moderated;

        return $this;
    }

    /**
     * Get moderated
     *
     * @return boolean
     */
    public function getModerated()
    {
        return $this->moderated;
    }

    /**
     * Set avatar
     *
     * @param string $avatar
     *
     * @return Comment
     */
    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * Get avatar
     *
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }
}

src/AppBundle/Resources/views/adminPanel.html.twig
{% extends "base.html.twig" %}
{% block body %}
    <div>
        <div>
            {% for comment in comments %}
                <p>
                    <div class="list-group-item" style="background: {{ comment.moderated  ? '#fff' : '#ccc' }}">
                        <h4 class="list-group-item-heading">
                        <a><img src="" class="img-responsive img-circle" alt="image" width="55" height="55"></a>
                            <i class="text-success"><strong>{{ comment.id }} ) </strong></i> {{- comment.userName -}}
                            <span class="text-muted"> ({{ comment.userEmail }})</span>
                            {{ comment.createdAt|date('d-m-Y H:i:s') }}
                            <div class="pull-right text-danger">
                                {% if comment.moderated %}
                                    {% set flag = 1 %}
                                    <a href="{{ path('edit', {'id': comment.id, 'action': 'hide'}) }}" class="btn text-primary btn-lg"><span class="glyphicon glyphicon-eye-close"></span></a>
                                {% else %}
                                    {% set flag = 0 %}
                                    <a href="{{ path('edit', {'id': comment.id, 'action': 'publish'}) }}"  class="btn text-success btn-lg"><span class="glyphicon glyphicon-ok-circle"></span></a>
                                {% endif %}
                                <a href="{{ path('delete', {'id': comment.id }) }}" class="btn text-danger btn-lg"><span class="glyphicon glyphicon-remove-circle"></span></a>
                            </div>
                        </h4>
                        <p class="list-group-item-text text-{{ flag == 1 ? 'muted' : 'primary' }}">{{ comment.comment|raw }}</p>
                    </div>
                </p>
            {% endfor %}
        </div>
    </div>
    <div class="navigation text-success text-center" style="font-size:35px">
        {{ knp_pagination_render(comments) }}
    </div>
{% endblock %}

src/AppBundle/Resources/views/comment.html.twig
{% extends "::base.html.twig" %}
{% block body %}
    {% if sort == 'desc' %}
        {% set order = 'asc' %}
    {% else %}
        {% set order = 'desc' %}
    {% endif %}
    <a href="{{ path('list', {'sort': order}) }}" class="btn btn-default">by date
        <span class="glyphicon glyphicon-menu-{{ sort == 'desc' ? 'down' : 'up' }}" aria-hidden="true"></span>
    </a>
    {% for comment in comments %}
        <div class="list-group-item">
            <h4 class="list-group-item-heading">
                {% if comment.avatar is empty %}
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                {% else %}
                    <img src="/avatar_user/avatar/{{ comment.avatar }}" class="img-responsive img-circle" alt="image" width="55" height="55">
                {% endif %}
                {{ loop.index }}) {{ comment.userName }}
                <span class="text-muted"> ({{ comment.userEmail }})</span>
                <div class="pull-right text-muted">
                    {{ comment.createdAtAsDate|date('d-m-Y H:i:s') }}
                </div>
            </h4>
            <p class="list-group-item-text text-info">{{ comment.comment|raw }}</p>
        </div>
    {% endfor %}
    <div class="navigation text-success text-center" style="font-size:35px">
        {{ knp_pagination_render(comments) }}
    </div>
    <div>
        <span class="pull-right">
            <a data-target="#answer-modal" data-toggle="modal" style="position: fixed; bottom: 50px; right: 50px"
               class="btn btn-danger" href="{{ path('add') }}">Add comment</a>
        </span>
    </div>
    <div class="modal fade" id="answer-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">loading...</div>
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/formAddComment.html.twig
{% if added %}
    <h2>Комментарий добавлен и будет отображен после модерации менеджером</h2>
    <script>
        $(document).ready(function(){
            setTimeout(function(){
                $('#answer-modal').modal('hide');
                setTimeout(function(){
                    $('#answer-modal').find('.hidden').removeClass('hidden');
                    $('#answer-modal').find('h2').addClass('hidden');
                }, 1000);
            }, 3000);
        });
    </script>
    <div class="hidden">
{% endif %}

    {{ form_start(form, {'attr': {'id': 'comment'} }) }}
        <div class="modal-header">
            <button type="button" class="close btn btn-danger" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">adding new comment</h4>
        </div>
        <div class="modal-body text-info">
            {{ form_row(form.userName, { 'attr': {'class': 'form-control'} }) }}
            {{ form_row(form.userEmail, { 'attr': {'class': 'form-control'} }) }}
            {{ form_row(form.avatar, { 'attr': {'class': 'form-control'} }) }}
            {{ form_row(form.comment, { 'attr': {'class': 'form-control'} }) }}
        </div>
        <div class="modal-footer">
            {{ form_row(form.send) }}
        </div>
    {{ form_end(form) }}

    <script>
        $(document).ready(function() {
            var files;
            $('#{{ form.avatar.vars.id }}').on('change', function(event) {
                files = event.target.files;
            });
            $('#comment').submit(function(e) {
                e.stopPropagation();
                e.preventDefault();
                var data = new FormData();
                data.append('{{ form.userName.vars.full_name }}', $('#{{ form.userName.vars.id }}').val());
                data.append('{{ form.userEmail.vars.full_name }}', $('#{{ form.userEmail.vars.id }}').val());
                data.append('{{ form.comment.vars.full_name }}', $('#{{ form.comment.vars.id }}').val());
                data.append('{{ form._token.vars.full_name }}', $('#{{ form._token.vars.id }}').val());

                $.each(files, function(key, value) {
                    data.append('{{ form.avatar.vars.full_name }}', value);
                });

                $.ajax({
                    url: $(this).prop('action'),
                    type: 'POST',
                    data: data,
                    cache: false,
                    processData: false,
                    contentType: false,
                    success: function(response) {
                        $('#answer-modal').find('.modal-content').html(response);
                    }
                });
                return false;
            });
        });
    </script>

{% if added %}
</div>
{% endif %}